const SECTIONS = [
  {
    id: 'overview',
    title: 'Oversikt',
    icon: '📋',
    subtitle: 'Forstå AI-reisen i utdanning',
    description:
      'Introduksjon til Microsoft Education AI Toolkit. Lær om tillit og intelligens som grunnprinsipper, og hvordan AI kan utvide pedagogisk kapasitet.',
    topics: [
      'Ledelse ved AI-fronten i utdanning',
      'Perspektiv for strategiske, pedagogiske og tekniske ledere',
      'Fem steg for AI-implementering',
      'Forskjellen mellom Copilot Chat og Microsoft 365 Copilot',
      'Microsoft Elevate for skoler og lokalsamfunn',
    ],
    steps: [
      { title: 'Utforskning og planlegging', desc: 'Identifiser pedagogiske mål AI kan styrke' },
      { title: 'Data og infrastruktur', desc: 'Styring, policy og sikkerhet' },
      { title: 'Pilot', desc: 'Opplæring og test i utvalgte klasser' },
      { title: 'Skalering', desc: 'Rull ut verktøy og samle tilbakemeldinger' },
      { title: 'Evaluering', desc: 'Mål effekt og juster planen' },
    ],
    link: 'https://learn.microsoft.com/education/',
  },
  {
    id: 'navigators',
    title: 'AI Navigators',
    icon: '🧭',
    subtitle: 'Beste praksis fra hele verden',
    description:
      'Globale eksempler fra institusjoner som leder an i AI-forskning, eksperimentering og utrulling i utdanning.',
    topics: [
      'Elevsuksess – personalisert læring og tilbakemelding',
      'Institusjonell innovasjon – effektivisering og innsikt',
      'Forenkle og sikre IT – beskyttelse og compliance',
      'Casestudier fra Hong Kong, NYC, California, Australia m.fl.',
    ],
    cases: [
      { name: 'EdUJCPS, Hong Kong', focus: 'GenAI-chatboter for matematikk og tilbakemelding' },
      { name: 'NYC Public Schools', focus: 'AI-assistent som multipliserer lærereffekt' },
      { name: 'CSU San Marcos', focus: 'Personlig studentoppfølging med Dynamics 365' },
      { name: 'South Australia', focus: 'Kreativitet og kritisk tenkning i klasserommet' },
    ],
    link: 'https://www.microsoft.com/en-us/education/blog',
  },
  {
    id: 'plan',
    title: 'Planlegg',
    icon: '📐',
    subtitle: 'Fra visjon til konkret plan',
    description:
      'Praktisk veiledning for å engasjere fellesskapet, definere mål, forberede data og styrke styring og retningslinjer.',
    topics: [
      'Engasjer skolemiljøet og foreldre',
      'Definer mål som er målbare og realistiske',
      'Forbered data og infrastruktur',
      'Styrk styring og retningslinjer (AUP, integritet, personvern)',
      'Bryt ned datasiloer mellom systemer',
    ],
    checklist: [
      'Opprett AI-ledergruppe med IT, pedagogikk og ledelse',
      'Vurder infrastruktur og policy-beredskap',
      'Oppdater retningslinjer for akademisk integritet',
      'Kartlegg datakilder og tilgangsstyring',
      'Definer suksesskriterier for piloten',
    ],
    link: 'https://aka.ms/AIforEducation',
  },
  {
    id: 'implement',
    title: 'Implementer',
    icon: '⚡',
    subtitle: 'Verktøy, prompting og agenter',
    description:
      'Velg riktige verktøy, lær effektiv prompting, bygg profesjonell læring og utforsk agenter for klasserom og administrasjon.',
    topics: [
      'Velg riktig AI-verktøy (kjøp, bygg eller hybrid)',
      'Effektiv prompting med Goal-Context-Source-Expectations',
      'Profesjonell læring og Microsoft Learn',
      'Bruk, bygg og utrull agenter med Copilot Studio',
      'AI Sparks for elevsuksess, innovasjon og IT',
    ],
    tools: [
      { name: 'Copilot Chat', tier: 'Gratis', use: 'Hverdagsassistent, idémyldring, bilder' },
      { name: 'Microsoft 365 Copilot', tier: 'Betalt', use: 'Integrert i Word, Excel, Teams, Outlook' },
      { name: 'Learning Accelerators', tier: 'Inkludert', use: 'Lesing, matte, søk, presentasjon' },
      { name: 'Minecraft Education', tier: 'Lisens', use: 'AI-kompetanse for yngre elever' },
      { name: 'Copilot Studio', tier: 'Avansert', use: 'Egendefinerte agenter for skolen' },
    ],
    link: 'https://m365copilot.com',
  },
  {
    id: 'research',
    title: 'Forskning',
    icon: '🔬',
    subtitle: 'Innsikt og evidens',
    description:
      'Microsoft-innsikt, akademisk forskning, planleggingsstøtte og thought leadership for informerte beslutninger.',
    topics: [
      'Microsoft Work Trend Index 2025',
      'Akademisk forskning og anbefalte bøker',
      'Datadrevet planleggingsstøtte',
      'Thought leadership fra utdanningsledere',
      'Malverk og maler for institusjoner',
    ],
    resources: [
      { title: 'AI Skills Navigator', url: 'https://learn.microsoft.com/training/' },
      { title: 'Digital Skills Compass', url: 'https://www.microsoft.com/en-us/worklab/' },
      { title: 'Prompt-a-thon for utdanning', url: 'https://learn.microsoft.com/education/' },
      { title: 'AI for Education learning path', url: 'https://learn.microsoft.com/training/paths/ai-for-education/' },
    ],
    link: 'https://www.microsoft.com/en-us/worklab/work-trend-index',
  },
];

const SUBJECTS = [
  {
    id: 'norsk',
    name: 'Norsk',
    level: 'Trinn 5–10 / VG',
    color: '#c42b2b',
    icon: '📖',
    aiUses: [
      'Tilbakemelding på tekster med fokus på struktur og argumentasjon',
      'Generere leseoppgaver på ulike nivåer',
      'Støtte kildekritikk og referansepraksis',
      'Hjelpe elever med omformulering uten å skrive ferdig teksten',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Kartlegg hvor AI passer i skriveprosessen (idé → utkast → revisjon)' },
      { phase: 'Uke 3–4', task: 'Piloter Copilot Chat for tilbakemelding på utkast i én klasse' },
      { phase: 'Uke 5–6', task: 'Etabler klasseregler for ansvarlig AI-bruk og kildehenvisning' },
      { phase: 'Uke 7–8', task: 'Del beste praksis på fagmøte og juster vurderingskriterier' },
      { phase: 'Uke 9–10', task: 'Evaluer elevprodukter og lærerarbeidsbelastning' },
    ],
    competencies: [
      'Forstå forskjellen mellom AI-assistanse og plagiat',
      'Bruke Goal-Context-Source-Expectations i prompts',
      'Tilpasse tilbakemeldinger til kompetansemål i LK20',
      'Veilede elever i faktasjekk og kildekritikk',
    ],
    prompt:
      'Du er en norsklærer. Lag en 45-minutters leksjon om argumenterende tekst for 9. trinn. Inkluder læringsmål, aktivitet med Copilot som sparringspartner (ikke ghostwriter), og vurderingskriterier.',
  },
  {
    id: 'matematikk',
    name: 'Matematikk',
    level: 'Trinn 1–10 / VG',
    color: '#0078d4',
    icon: '🔢',
    aiUses: [
      'Generere varierte oppgaver med stigende vanskelighetsgrad',
      'Forklare løsningstrinn på elevens nivå',
      'Identifisere typiske feil i elevbesvarelser',
      'Visualisere funksjoner og geometri med Copilot',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Definer når AI skal forklare vs. når eleven skal regne selv' },
      { phase: 'Uke 3–4', task: 'Test AI-genererte oppgaver mot eksisterende læreplanmål' },
      { phase: 'Uke 5–6', task: 'Bruk Math Progress og Copilot for differensiering' },
      { phase: 'Uke 7–8', task: 'Innfør «vis meg hvordan»-prompts fremfor fasitsvar' },
      { phase: 'Uke 9–10', task: 'Mål om faglig dialog og problemløsningsstrategi hos elever' },
    ],
    competencies: [
      'Designe prompts som fremmer forståelse, ikke juks',
      'Bruke Math Progress for innsikt i elevutfordringer',
      'Vurdere AI-genererte oppgavers kvalitet',
      'Integrere AI i formativ vurdering',
    ],
    prompt:
      'Lag 5 matematikkoppgaver om brøk for 7. trinn med stigende vanskelighetsgrad. For hver oppgave: gi hint-strategi (ikke full løsning) og typiske feil elever gjør.',
  },
  {
    id: 'engelsk',
    name: 'Engelsk',
    level: 'Trinn 1–10 / VG',
    color: '#107c10',
    icon: '🌍',
    aiUses: [
      'Samtaleøving og uttaletrening med AI',
      'Tilbakemelding på grammatikk og ordforråd',
      'Generere autentiske lesetekster på CEFR-nivå',
      'Støtte muntlig presentasjon med Speaker Coach',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Kartlegg CEFR-nivåer og hvor AI kan støtte muntlig/muntlig' },
      { phase: 'Uke 3–4', task: 'Piloter samtaleøving med Copilot Chat på valgt tema' },
      { phase: 'Uke 5–6', task: 'Bruk Speaker Coach i Teams for presentasjonsøving' },
      { phase: 'Uke 7–8', task: 'Utvikle vurderingsrubrikker som inkluderer AI-bruk' },
      { phase: 'Uke 9–10', task: 'Evaluer muntlig ferdighetsutvikling og elevtrygghet' },
    ],
    competencies: [
      'Tilpasse AI-dialog til CEFR-nivå (A1–B2)',
      'Bruke Speaker Coach og Speaker Progress',
      'Balansere AI-øving med autentisk kommunikasjon',
      'Vurdere muntlige ferdigheter med og uten AI',
    ],
    prompt:
      'Simuler en B1-samtale om bærekraft. Still oppfølgingsspørsmål, korriger høflig grammatikkfeil, og gi tilbakemelding på ordforråd etter samtalen.',
  },
  {
    id: 'naturfag',
    name: 'Naturfag',
    level: 'Trinn 8–10 / VG',
    color: '#008272',
    icon: '🔬',
    aiUses: [
      'Visualisere naturprosesser og eksperimentoppsett',
      'Generere hypoteser og diskusjonsspørsmål',
      'Støtte laboratorierapporter og kildebruk',
      'Forklare komplekse sammenhenger med analogier',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Identifiser temaer der visualisering styrker forståelse' },
      { phase: 'Uke 3–4', task: 'Bruk AI til å generere hypotese- og diskusjonsspørsmål' },
      { phase: 'Uke 5–6', task: 'Piloter laboratorierapport-støtte med kildekrav' },
      { phase: 'Uke 7–8', task: 'Undervis i vitenskapelig metode vs. AI-hallusinasjoner' },
      { phase: 'Uke 9–10', task: 'Evaluer elevforståelse av naturfaglig tenkning' },
    ],
    competencies: [
      'Skille mellom AI-forklaringer og vitenskapelige kilder',
      'Designe undersøkelser med AI som planleggingsverktøy',
      'Veilede elever i laboratorierapporter',
      'Fremme kritisk tenkning om AI-generert «fakta»',
    ],
    prompt:
      'Lag en naturfagtime om fotosyntese for 9. trinn. Inkluder demonstrasjon, AI-generert infografikk-beskrivelse, og 5 diskusjonsspørsmål om energiomsetning.',
  },
  {
    id: 'samfunnsfag',
    name: 'Samfunnsfag',
    level: 'Trinn 8–10 / VG',
    color: '#8764b8',
    icon: '🏛️',
    aiUses: [
      'Analysere nyhetsartikler og identifisere bias',
      'Simulere debatter og rollespill',
      'Sammenligne perspektiver på samfunnsspørsmål',
      'Støtte kildekritikk med Search Coach',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Etabler rammer for AI i debatt og kildeanalyse' },
      { phase: 'Uke 3–4', task: 'Bruk Search Coach for informasjonskompetanse' },
      { phase: 'Uke 5–6', task: 'Piloter bias-analyse av AI-svar på samfunnstema' },
      { phase: 'Uke 7–8', task: 'Rollespill med AI som motpart i demokratitemaer' },
      { phase: 'Uke 9–10', task: 'Evaluer elevers kildekritikk og argumentasjon' },
    ],
    competencies: [
      'Identifisere bias i AI-genererte svar',
      'Bruke Search Coach og Search Progress',
      'Knytte AI-aktiviteter til demokrati og medborgerskap',
      'Vurdere argumentasjonskvalitet uavhengig av verktøy',
    ],
    prompt:
      'Presenter to motstridende perspektiver på digital mediedannelse. Etterpå: hjelp eleven å identifisere bias, manglende kilder og styrker i begge argumentene.',
  },
  {
    id: 'krle',
    name: 'KRLE',
    level: 'Trinn 1–10',
    color: '#ca5010',
    icon: '🕊️',
    aiUses: [
      'Utforske verdier og etiske dilemmaer',
      'Sammenligne tradisjoner med respekt og nøyaktighet',
      'Støtte refleksjonsoppgaver med Reflect',
      'Generere case-studier for etikkdiskusjon',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Definer etiske retningslinjer for AI i verdiedukasjon' },
      { phase: 'Uke 3–4', task: 'Bruk Reflect for elevs refleksjon om livsmestring' },
      { phase: 'Uke 5–6', task: 'Test AI-genererte etiske dilemmaer i smågrupper' },
      { phase: 'Uke 7–8', task: 'Faktasjekk AI-svar om religion og livssyn sammen' },
      { phase: 'Uke 9–10', task: 'Evaluer dybde i elevrefleksjon og respekt i diskusjon' },
    ],
    competencies: [
      'Faktasjekke AI om religion og livssyn',
      'Bruke Reflect for sosial-emosjonell læring',
      'Fasilitere etiske diskusjoner med AI-støtte',
      'Sikre inkluderende og respektfulle aktiviteter',
    ],
    prompt:
      'Lag et etisk dilemma om teknologi og privatliv for 8. trinn. Inkluder refleksjonsspørsmål om verdier, og veiledning for respektfull klassediskusjon.',
  },
  {
    id: 'kunst',
    name: 'Kunst og håndverk',
    level: 'Trinn 1–10 / VG',
    color: '#e3008c',
    icon: '🎨',
    aiUses: [
      'Idémyldring og moodboards med bildegenerering',
      'Analysere kunstverk og stilretninger',
      'Støtte prosessdokumentasjon',
      'Eksperimentere med komposisjon og farge',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Avklar opphavsrett og AI i kreative prosesser' },
      { phase: 'Uke 3–4', task: 'Bruk bildegenerering for idémyldring, ikke ferdig produkt' },
      { phase: 'Uke 5–6', task: 'Piloter prosessdokumentasjon med AI-refleksjon' },
      { phase: 'Uke 7–8', task: 'Diskuter AI-kunst vs. menneskelig skaperglede' },
      { phase: 'Uke 9–10', task: 'Utstilling med refleksjon om AI i kreativ prosess' },
    ],
    competencies: [
      'Bruke AI for idéfase, ikke erstatte håndverk',
      'Forstå opphavsrett ved AI-genererte bilder',
      'Dokumentere kreativ prosess',
      'Reflektere over estetikk og teknologi',
    ],
    prompt:
      'Generer tre ulike moodboard-beskrivelser for et prosjekt om «bærekraft i design». Eleven velger én retning og forklarer valget i egen ord.',
  },
  {
    id: 'programfag',
    name: 'Programfag / YFF',
    level: 'VG1–VG3',
    color: '#4f6bed',
    icon: '⚙️',
    aiUses: [
      'GitHub Copilot for programmering og paired programming',
      'Generere teknisk dokumentasjon',
      'Simulere arbeidsoppgaver og HMS-scenarier',
      'Bygge agenter for bransjespesifikke oppgaver',
    ],
    plan: [
      { phase: 'Uke 1–2', task: 'Innfør GitHub Copilot med etiske retningslinjer for koding' },
      { phase: 'Uke 3–4', task: 'Parprogrammering-økter med AI som sparringspartner' },
      { phase: 'Uke 5–6', task: 'Prosjekt: bygg en enkel agent med Copilot Studio' },
      { phase: 'Uke 7–8', task: 'Koble AI-kompetanse til læreplan i yrkesfag' },
      { phase: 'Uke 9–10', task: 'Karriereplan: AI i bransjen eleven sikter mot' },
    ],
    competencies: [
      'Bruke GitHub Copilot ansvarlig i kodeprosjekter',
      'Forstå AI i arbeidslivet eleven sikter mot',
      'Bygge enkle agenter med lavkode-verktøy',
      'Dokumentere tekniske løsninger',
    ],
    prompt:
      'Som faglærer i IT: design en 2-timers økt om paired programming med GitHub Copilot. Inkluder etikk, debugging-strategi og vurderingskriterier.',
  },
];

const LEARNING_MODULES = [
  {
    id: 'mod-intro',
    section: 'overview',
    title: 'Introduksjon til AI i utdanning',
    duration: '30 min',
    type: 'Grunnleggende',
    items: [
      'Les om tillit og intelligens som grunnprinsipper',
      'Forstå «frontier moment» i utdanning',
      'Gjennomgå de fem implementeringsstegene',
      'Reflekter over din rolle som lærer i AI-tiden',
    ],
  },
  {
    id: 'mod-copilot',
    section: 'implement',
    title: 'Copilot Chat vs. Microsoft 365 Copilot',
    duration: '45 min',
    type: 'Verktøy',
    items: [
      'Logg inn på Copilot Chat med skolekonto',
      'Test gratis funksjoner: chat, bilde, opplasting',
      'Sammenlign med betalte Copilot-funksjoner i M365',
      'Vurder hva som er relevant for ditt fag',
    ],
  },
  {
    id: 'mod-prompting',
    section: 'implement',
    title: 'Effektiv prompting for lærere',
    duration: '60 min',
    type: 'Praksis',
    items: [
      'Lær Goal-Context-Source-Expectations-rammeverket',
      'Øv på dårlig vs. god prompt (før/etter)',
      'Lag 3 fagspesifikke prompts for ditt fag',
      'Test prompts med kolleger på fagmøte',
    ],
  },
  {
    id: 'mod-ethics',
    section: 'plan',
    title: 'Ansvarlig AI-bruk i klasserommet',
    duration: '45 min',
    type: 'Policy',
    items: [
      'Gjennomgå 7 retningslinjer for elever',
      'Utkast til klasseregler for AI-bruk',
      'Diskuter akademisk integritet med kolleger',
      'Tilpass skolens AUP til ditt fag',
    ],
  },
  {
    id: 'mod-accelerators',
    section: 'implement',
    title: 'Learning Accelerators i praksis',
    duration: '50 min',
    type: 'Verktøy',
    items: [
      'Utforsk Reading Coach og Reading Progress',
      'Test Search Coach for informasjonskompetanse',
      'Prøv Speaker Coach for muntlige presentasjoner',
      'Planlegg én aktivitet med accelerator i undervisningen',
    ],
  },
  {
    id: 'mod-agents',
    section: 'implement',
    title: 'Agenter og automatisering',
    duration: '75 min',
    type: 'Avansert',
    items: [
      'Forstå hva agentic AI betyr for skolen',
      'Utforsk Copilot Studio og Agent Store',
      'Identifiser én arbeidsoppgave som kan automatiseres',
      'Vurder sikkerhet og styring ved agent-bruk',
    ],
  },
  {
    id: 'mod-community',
    section: 'navigators',
    title: 'Lær av andre institusjoner',
    duration: '40 min',
    type: 'Inspirasjon',
    items: [
      'Les 2 casestudier fra AI Navigators',
      'Noter 3 guiding questions for din skole',
      'Del funn med AI-ledergruppen',
      'Identifiser én idé å pilotere',
    ],
  },
  {
    id: 'mod-research',
    section: 'research',
    title: 'Evidens og videre læring',
    duration: '35 min',
    type: 'Forskning',
    items: [
      'Utforsk Microsoft AI Skills Navigator',
      'Ta Digital Skills Compass-vurderingen',
      'Finn relevant læringssti på Microsoft Learn',
      'Sett deg et kompetansemål for semesteret',
    ],
  },
];
