const SUBJECT_DETAILS = {
  norsk: {
    intro:
      'I norskfaget er AI mest verdifullt som sparringspartner i skrive- og leseprosessen – ikke som ghostwriter. Fokuset ligger på kildekritikk, tekststruktur og elevens egen stemme.',
    lk20: [
      'Muntlig og skriftlig kommunikasjon på ulike målformer',
      'Kritisk vurdering av kilder og bruk av referanser',
      'Kreativitet og refleksjon over egen læring',
      'Digitale ferdigheter og mediekompetanse',
    ],
    tools: [
      { name: 'Copilot Chat', use: 'Tilbakemelding på utkast, omformulering, idémyldring' },
      { name: 'Reading Coach', use: 'Lesefluens for elever med uttaleøving' },
      { name: 'Reading Progress', use: 'Kartlegge leseferdighet og lesevaner' },
      { name: 'Word + Copilot', use: 'Strukturere tekster og sammenfatte kilder' },
    ],
    weeks: [
      { week: 1, title: 'Kartlegging', activity: 'Undersøk skriveprosessen i klassen: hvor stopper elevene seg? Intervju 3 elever.' },
      { week: 2, title: 'Policy', activity: 'Lag klasseregler for AI i skriving sammen med elevene. Heng opp plakat.' },
      { week: 3, title: 'Pilot start', activity: 'Én skriveoppgave der Copilot gir tilbakemelding på struktur – ikke innhold.' },
      { week: 4, title: 'Kildebruk', activity: 'Øvelse: faktasjekk AI-genererte påstander med troverdige kilder.' },
      { week: 5, title: 'Lesing', activity: 'Bruk Reading Coach i 2 leseøkter. Sammenlign med tradisjonell lesing.' },
      { week: 6, title: 'Revisjon', activity: '«Tre-utkast-metoden»: idéutkast → AI-sparring → egen revisjon.' },
      { week: 7, title: 'Vurdering', activity: 'Utvikle rubrikk som skiller prosess, produkt og AI-bruk.' },
      { week: 8, title: 'Fagmøte', activity: 'Del erfaringer med kolleger. Samle gode og dårlige prompter.' },
      { week: 9, title: 'Skalering', activity: 'Rull ut til flere klasser. Tilpass for muntlig og skriftlig.' },
      { week: 10, title: 'Evaluering', activity: 'Sammenlign elevtekster før/etter. Juster plan for neste semester.' },
    ],
    lessons: [
      {
        title: 'Argumenterende tekst med AI-sparring',
        duration: '2 × 45 min',
        goal: 'Eleven skriver argumenterende tekst med AI som strukturcoach',
        steps: ['Introduksjon til ansvarlig bruk (15 min)', 'Individuell skriving med Copilot-sparring (30 min)', 'Peer review uten AI (30 min)', 'Refleksjon om hva AI hjalp med (15 min)'],
      },
      {
        title: 'Kildekritikk og AI',
        duration: '45 min',
        goal: 'Eleven identifiserer feil og bias i AI-generert tekst',
        steps: ['AI genererer tekst om aktuelt tema (10 min)', 'Eleven faktasjekker med minst 3 kilder (25 min)', 'Klassediskusjon om hva som var feil (10 min)'],
      },
      {
        title: 'Kreativ skriving – idéfase',
        duration: '45 min',
        goal: 'Bruke AI til idémyldring, skrive ferdig selv',
        steps: ['Brainstorm med AI: 5 ulike vinklinger (15 min)', 'Velg én idé og skriv utkast uten AI (25 min)', 'Del utdrag i par (5 min)'],
      },
    ],
    prompts: [
      'Gi tilbakemelding på strukturen i denne teksten. Ikke skriv om – pek på svake punkter og foreslå forbedringer.',
      'Lag 3 leseoppgaver på ulikt nivå om samme novelle. Inkluder forståelse, tolkning og refleksjon.',
      'Hjelp eleven å omformulere dette avsnittet tydeligere, men behold elevens ordvalg så langt det er mulig.',
    ],
    assessment: [
      'Vurder skriveprosess og refleksjon – ikke bare sluttprodukt',
      'Krev dokumentasjon av AI-bruk i innlevering',
      'Skill mellom formativ AI-støtte og summativ vurdering uten AI',
      'Vurder kildehenvisning og faktasjekk eksplisitt',
    ],
    studentRules: [
      'AI er sparringspartner – du er forfatteren',
      'Alltid faktasjekk AI-generert innhold',
      'Oppgi hvordan du brukte AI i innleveringen',
      'Under prøver gjelder egne regler – spør lærer',
    ],
    teacherPath: [
      'Les toolkit-seksjonen om ansvarlig AI-bruk',
      'Øv på 5 tilbakemeldings-prompter i Copilot Chat',
      'Gjennomfør pilot i én klasse',
      'Delta på fagmøte og del rubrikk',
    ],
  },

  matematikk: {
    intro:
      'Matematikk krever at eleven tenker selv. AI skal forklare, gi hint og generere oppgaver – aldri levere fasitsvar uten forståelse.',
    lk20: [
      'Problemløsning og matematisk resonnering',
      'Kommunikasjon av matematiske ideer',
      'Bruk av digitale verktøy i utforskning',
      'Modellering og anvendelse i kontekst',
    ],
    tools: [
      { name: 'Copilot Chat', use: 'Forklaringer på elevnivå, oppgavegenerering' },
      { name: 'Math Progress', use: 'Analysere elevfeil og tilpasse øving' },
      { name: 'Excel + Copilot', use: 'Visualisere funksjoner og datasett' },
      { name: 'GeoGebra / Copilot', use: 'Geometri og grafer' },
    ],
    weeks: [
      { week: 1, title: 'Prinsipper', activity: 'Definer «hint, ikke svar»-regelen. Lag plakat for klasserommet.' },
      { week: 2, title: 'Oppgaver', activity: 'Generer 20 oppgaver med AI – vurder kvalitet mot læreplan.' },
      { week: 3, title: 'Pilot', activity: 'Formativ økt: elever spør AI om hint ved fastsatte tidspunkt.' },
      { week: 4, title: 'Feilanalyse', activity: 'Bruk typiske feil fra Math Progress i undervisningen.' },
      { week: 5, title: 'Differensiering', activity: 'Tre oppgavesett (lett/medium/vanskelig) generert og kuratert.' },
      { week: 6, title: 'Dialog', activity: '«Forklar til en 10-åring»-metode med AI som kontrollør.' },
      { week: 7, title: 'Prøveforberedelse', activity: 'Øvingsmodus uten AI vs. læringsmodus med AI – tydelig skill.' },
      { week: 8, title: 'Kollegialt', activity: 'Del gode prompter på fagmøte. Test hverandres oppgaver.' },
      { week: 9, title: 'Elevrefleksjon', activity: 'Elever skriver: «Hva lærte jeg av AI-hintene?»' },
      { week: 10, title: 'Evaluering', activity: 'Mål problemløsningsstrategi – ikke bare riktig svar.' },
    ],
    lessons: [
      {
        title: 'Brøk med hint-strategi',
        duration: '45 min',
        goal: 'Eleven løser brøkoppgaver med AI som hintgiver',
        steps: ['Kort intro om hint-regelen (5 min)', 'Individuell problemløsning med Copilot (25 min)', 'Felles gjennomgang av strategier (15 min)'],
      },
      {
        title: 'Funksjoner og visualisering',
        duration: '45 min',
        goal: 'Koble algebraisk og grafisk forståelse',
        steps: ['Copilot forklarer sammenheng (10 min)', 'Elever tegner grafer i Excel/GeoGebra (25 min)', 'Sammenlign og diskuter (10 min)'],
      },
      {
        title: 'Feilanalyse i par',
        duration: '45 min',
        goal: 'Forstå vanlige feil og hvorfor de skjer',
        steps: ['Vis anonyme feil fra klassekamerater (10 min)', 'Par diskuterer med AI-hint (20 min)', 'Presentér funn (15 min)'],
      },
    ],
    prompts: [
      'Gi meg et hint til denne oppgaven uten å vise løsningen. Spør meg hva jeg har prøvd først.',
      'Lag 5 oppgaver om [tema] for [trinn] med stigende vanskelighetsgrad. Inkluder løsningsforslag for lærer.',
      'Forklar denne løsningen som om jeg er 12 år. Bruk en analogi fra hverdagen.',
    ],
    assessment: [
      'Vurder resonnering og fremgangsmåte eksplisitt',
      'Under prøver: ingen AI med mindre eksplisitt tillatt',
      'Formativ bruk: loggfør hint som del av læringsprosessen',
      'Se etter overfladisk kopiering av AI-forklaringer',
    ],
    studentRules: [
      'Spør om hint – ikke om fasit',
      'Forklar løsningen din muntlig etter AI-hjelp',
      'Under prøver: følg lærerens regler',
      'AI kan hjelpe deg forstå – ikke gjøre arbeidet for deg',
    ],
    teacherPath: [
      'Test 10 oppgave-prompter og vurder kvalitet',
      'Sett opp Math Progress for én klasse',
      'Definer tydelig skille prøve vs. øving',
      'Lag fagfelles prompt-bibliotek',
    ],
  },

  engelsk: {
    intro:
      'Engelskfaget passer godt for AI-samtaler, uttaletrening og differensiert innhold på CEFR-nivå. Balansen mellom AI-øving og autentisk kommunikasjon er nøkkelen.',
    lk20: [
      'Muntlig og skriftlig kommunikasjon på engelsk',
      'Kulturell kompetanse og forståelse',
      'Strategier for språklæring',
      'Digitale ressurser for språkutvikling',
    ],
    tools: [
      { name: 'Copilot Chat', use: 'Samtaleøving, grammatikk, ordforråd' },
      { name: 'Speaker Coach', use: 'Tilbakemelding på tempo, fyllord, klarhet' },
      { name: 'Speaker Progress', use: 'Spor muntlige ferdigheter over tid' },
      { name: 'Reading Coach', use: 'Uttale og leseflyt på engelsk' },
    ],
    weeks: [
      { week: 1, title: 'CEFR-kart', activity: 'Kartlegg klassens nivåer. Match AI-dialog til A1–B2.' },
      { week: 2, title: 'Samtalepilot', activity: '10 min daglig AI-samtale om valgfritt tema.' },
      { week: 3, title: 'Grammatikk', activity: 'Copilot forklarer feil – eleven retter selv.' },
      { week: 4, title: 'Speaker Coach', activity: 'Presentasjonsøving med Coach i Teams.' },
      { week: 5, title: 'Lesing', activity: 'Generer tekster på riktig nivå + forståelsesspørsmål.' },
      { week: 6, title: 'Skriving', activity: 'E-post/essay med AI som korrekturleser – ikke forfatter.' },
      { week: 7, title: 'Kultur', activity: 'Sammenlign AI-beskrivelser av kultur med autentiske kilder.' },
      { week: 8, title: 'Vurdering', activity: 'Rubrikk for muntlig med og uten AI-øving.' },
      { week: 9, title: 'Autentisk', activity: 'Videochat med engelsktalende skole (eller pennevenn-prosjekt).' },
      { week: 10, title: 'Evaluering', activity: 'Mål trygghet og flyt – elevspørreundersøkelse.' },
    ],
    lessons: [
      {
        title: 'B1-samtale om bærekraft',
        duration: '45 min',
        goal: 'Øve flyt og ordforråd i dialog',
        steps: ['Modellering med Copilot (10 min)', 'Par-øving med AI (20 min)', 'Oppsummer nye ord (10 min)', 'Kort muntlig presentasjon (5 min)'],
      },
      {
        title: 'Presentasjon med Speaker Coach',
        duration: '45 min',
        goal: 'Forbedre muntlig presentasjonsteknikk',
        steps: ['Forberedelse (15 min)', 'Øv i Teams med Speaker Coach (20 min)', 'Revidér basert på tilbakemelding (10 min)'],
      },
      {
        title: 'Kildekritikk på engelsk',
        duration: '45 min',
        goal: 'Vurdere engelskspråklige kilder kritisk',
        steps: ['AI-oppsummering av artikkel (10 min)', 'Finn motstridende kilder (25 min)', 'Diskuter troverdighet (10 min)'],
      },
    ],
    prompts: [
      'Let\'s have a B1 conversation about [topic]. Ask follow-up questions. Correct my grammar gently after each reply.',
      'Create a reading text at A2 level about [topic] with 5 comprehension questions.',
      'I will present for 2 minutes. After, give feedback on vocabulary range and sentence structure.',
    ],
    assessment: [
      'Vurder muntlig kommunikasjon separat fra AI-øvingsprosess',
      'Dokumenter om AI ble brukt i forberedelse',
      'CEFR-nivå som referanseramme i tilbakemelding',
      'Autentisk produksjon uten AI ved summativ vurdering',
    ],
    studentRules: [
      'Bruk AI for å øve – ikke for å levere innleveringer',
      'Si fra om du brukte AI i forberedelsen',
      'Prøv å snakke engelsk med AI daglig',
      'Faktasjekk informasjon fra AI-samtaler',
    ],
    teacherPath: [
      'Kartlegg CEFR-nivåer i klassen',
      'Test Speaker Coach selv først',
      'Lag 3 samtaleprompter per tema',
      'Etabler muntlig vurderingsrubrikk',
    ],
  },

  naturfag: {
    intro:
      'Naturfag handler om undersøkelse og vitenskapelig tenkning. AI hjelper med visualisering og hypoteser, men eleven må alltid verifisere mot pålitelige kilder.',
    lk20: [
      'Naturvitenskapelige arbeidsmåter og modeller',
      'Undersøkelser og bruk av data',
      'Bærekraft og etiske vurderinger',
      'Teknologi og samfunn',
    ],
    tools: [
      { name: 'Copilot Chat', use: 'Forklaringer, hypoteser, visualiseringsbeskrivelser' },
      { name: 'Search Coach', use: 'Finne og vurdere vitenskapelige kilder' },
      { name: 'PowerPoint + Copilot', use: 'Presentasjoner av forsøk og resultater' },
      { name: 'Excel + Copilot', use: 'Datainnsamling og grafer' },
    ],
    weeks: [
      { week: 1, title: 'Metode', activity: 'Undervis i vitenskapelig metode vs. AI-hallusinasjoner.' },
      { week: 2, title: 'Visualisering', activity: 'AI beskriver prosesser – eleven tegner/modellerer.' },
      { week: 3, title: 'Hypoteser', activity: 'Generer hypoteser med AI – design forsøk for å teste.' },
      { week: 4, title: 'Laboratorium', activity: 'Laboratorierapport med krav om minst 3 kilder.' },
      { week: 5, title: 'Search Coach', activity: 'Øvelse i å finne troverdige naturvitenskapelige kilder.' },
      { week: 6, title: 'Diskusjon', activity: 'AI presenterer kontroversielt påstand – eleven debatterer.' },
      { week: 7, title: 'Bærekraft', activity: 'Case-studie med AI-støtte og faktasjekk.' },
      { week: 8, title: 'Tverrfaglig', activity: 'Koble naturfag med matematikk (data) og norsk (rapport).' },
      { week: 9, title: 'Presentasjon', activity: 'Elevgrupper presenterer undersøkelser.' },
      { week: 10, title: 'Evaluering', activity: 'Vurder forståelse av metode – ikke bare fakta.' },
    ],
    lessons: [
      {
        title: 'Fotosyntese – forståelse og modell',
        duration: '45 min',
        goal: 'Forstå energiomsetning i planter',
        steps: ['Demonstrasjon (10 min)', 'AI forklarer – eleven lager tegning (20 min)', 'Diskusjonsspørsmål (15 min)'],
      },
      {
        title: 'Vitenskapelig metode',
        duration: '2 × 45 min',
        goal: 'Designe og gjennomføre enkelt forsøk',
        steps: ['Hypotese med AI-støtte (20 min)', 'Forsøk i lab (45 min)', 'Rapport med kilder (25 min)'],
      },
      {
        title: 'AI-feil som læringsmoment',
        duration: '45 min',
        goal: 'Identifisere feil i AI-forklaringer',
        steps: ['Del AI-tekst med feil (5 min)', 'Faktasjekk i grupper (30 min)', 'Presentér funn (10 min)'],
      },
    ],
    prompts: [
      'Forklar [prosess] for 8.-klassing. Inkluder en hverdagsanalogi. Merk: jeg skal faktasjekke alt.',
      'Foreslå 3 testbare hypoteser om [tema]. Forklar hvordan vi kan teste dem i skolelab.',
      'Hva er vanlige misforståelser om [tema]? Lag en sjekkliste for eleven.',
    ],
    assessment: [
      'Vurder metode og kildebruk – ikke bare korrekte fakta',
      'Krev at AI-påstander er verifisert',
      'Laboratorierapporter med refleksjon over kilder',
      'Se etter forståelse gjennom muntlig forklaring',
    ],
    studentRules: [
      'Verifiser alltid naturvitenskapelige påstander fra AI',
      'Bruk minst 3 troverdige kilder i rapporter',
      'AI kan hjelpe med idéer – du gjennomfører forsøket',
      'Merk AI-bruk i laboratorierapporten',
    ],
    teacherPath: [
      'Test AI på typiske elevspørsmål – finn hallusinasjoner',
      'Lag kildebank for klassen',
      'Piloter Search Coach-økt',
      'Utvikle rapportmal med kildekrav',
    ],
  },

  samfunnsfag: {
    intro:
      'Samfunnsfag og AI møtes i kildekritikk, debatt og demokratisk dannelse. Eleven må lære å se bias i både medier og AI-svar.',
    lk20: [
      'Demokrati, medborgerskap og menneskerettigheter',
      'Økonomi og bærekraftig utvikling',
      'Kritisk tenkning og kildebruk',
      'Deltakelse og medbestemmelse',
    ],
    tools: [
      { name: 'Copilot Chat', use: 'Debatmotpart, perspektivanalyse, rollespill' },
      { name: 'Search Coach', use: 'Informasjonskompetanse og kildekritikk' },
      { name: 'Search Progress', use: 'Overvåke elevers søkestrategier' },
      { name: 'Copilot i Edge', use: 'Analysere nettartikler i sanntid' },
    ],
    weeks: [
      { week: 1, title: 'Bias', activity: 'Analyser AI-svar om politisk tema – finn skjevheter.' },
      { week: 2, title: 'Search Coach', activity: 'Øvelse: finn troverdige kilder om aktuelt tema.' },
      { week: 3, title: 'Debat', activity: 'AI som motpart i strukturert debatt.' },
      { week: 4, title: 'Nyhetsanalyse', activity: 'Sammenlign AI-oppsummering med originalartikkel.' },
      { week: 5, title: 'Rollespill', activity: 'AI spiller ulike samfunnsroller – eleven argumenterer.' },
      { week: 6, title: 'Demokrati', activity: 'Case: digital mediedannelse og valg.' },
      { week: 7, title: 'Økonomi', activity: 'AI forklarer økonomiske begreper – eleven gir eksempler.' },
      { week: 8, title: 'Prosjekt', activity: 'Gruppeprosjekt med krav om mangfoldige kilder.' },
      { week: 9, title: 'Presentasjon', activity: 'Debatt i klassen med eksplisitt kildebruk.' },
      { week: 10, title: 'Evaluering', activity: 'Vurder argumentasjon og kildekritikk.' },
    ],
    lessons: [
      {
        title: 'Bias i AI-svar',
        duration: '45 min',
        goal: 'Identifisere skjevhet i AI-genererte argumenter',
        steps: ['AI gir to perspektiver (10 min)', 'Elever analyserer bias (25 min)', 'Felles oppsummering (10 min)'],
      },
      {
        title: 'Demokratisk debatt',
        duration: '45 min',
        goal: 'Strukturert argumentasjon med kilder',
        steps: ['Debatregler (5 min)', 'Forberedelse med Search Coach (20 min)', 'Debatt (15 min)', 'Refleksjon (5 min)'],
      },
      {
        title: 'Medieanalyse',
        duration: '45 min',
        goal: 'Sammenligne kilder og vurdere troverdighet',
        steps: ['Velg aktuell sak (5 min)', 'AI + nett-kilder (30 min)', 'Klassediskusjon (10 min)'],
      },
    ],
    prompts: [
      'Presenter to motstridende syn på [tema]. Etterpå: hjelp meg identifisere bias og manglende kilder.',
      'Spill motpart i debatt om [tema]. Bruk saklige argumenter jeg kan imøtegå.',
      'Lag 5 kildekritiske spørsmål om denne nyhetssaken.',
    ],
    assessment: [
      'Vurder kvalitet på kilder og argumentasjon',
      'Krev mangfold av perspektiver i prosjekter',
      'Skill AI-assistert research fra egen analyse',
      'Muntlig debatt uten AI-notater ved vurdering',
    ],
    studentRules: [
      'Sjekk alltid AI-påstander mot troverdige kilder',
      'Bruk minst to ulike kildetyper i prosjekter',
      'AI i debattøving – ikke i innlevert analyse',
      'Oppgi kilder og AI-bruk tydelig',
    ],
    teacherPath: [
      'Test AI-bias på aktuelle politiske temaer',
      'Sett opp Search Coach for klassen',
      'Lag debattstruktur med vurderingskriterier',
      'Samle pålitelige kilder for vanlige temaer',
    ],
  },

  krle: {
    intro:
      'I KRLE er respekt og nøyaktighet avgjørende. AI kan støtte refleksjon og etiske dilemmaer, men fakta om religion og livssyn må alltid verifiseres.',
    lk20: [
      'Religioner, livssyn og etikk',
      'Identitet, mangfold og respekt',
      'Filosofiske og eksistensielle spørsmål',
      'Demokrati og medmenneskelighet',
    ],
    tools: [
      { name: 'Copilot Chat', use: 'Etiske dilemmaer, refleksjonsspørsmål' },
      { name: 'Reflect', use: 'Elevs emosjonelle refleksjon og trivsel' },
      { name: 'Copilot Chat', use: 'Sammenligne tradisjoner (med faktasjekk)' },
      { name: 'OneNote + Copilot', use: 'Refleksjonsjournaler' },
    ],
    weeks: [
      { week: 1, title: 'Etikk', activity: 'Etabler retningslinjer for AI i verdiedukasjon.' },
      { week: 2, title: 'Respekt', activity: 'Diskuter hva som er upassende å spørre AI om.' },
      { week: 3, title: 'Reflect', activity: 'Introduksjon til Reflect for livsmestring-refleksjon.' },
      { week: 4, title: 'Dilemma', activity: 'AI-generert etisk dilemma – smågruppediskusjon.' },
      { week: 5, title: 'Faktasjekk', activity: 'Sammenlign AI om religion med lærebok/ekspertkilde.' },
      { week: 6, title: 'Filosofi', activity: 'Refleksjonsspørsmål om eksistens og teknologi.' },
      { week: 7, title: 'Mangfold', activity: 'Inviter gjest om livssyn – ikke erstatt med AI.' },
      { week: 8, title: 'Prosjekt', activity: 'Refleksjonsoppgave med kildekrav.' },
      { week: 9, title: 'Dialog', activity: 'Strukturert klassedialog med klare regler.' },
      { week: 10, title: 'Evaluering', activity: 'Vurder dybde i refleksjon og respekt i diskusjon.' },
    ],
    lessons: [
      {
        title: 'Etisk dilemma – teknologi og privatliv',
        duration: '45 min',
        goal: 'Reflektere over verdier i teknologispørsmål',
        steps: ['Presentér dilemma (10 min)', 'Smågruppediskusjon (25 min)', 'Reflect-innsjekk (5 min)', 'Oppsummering (5 min)'],
      },
      {
        title: 'Faktasjekk om religion',
        duration: '45 min',
        goal: 'Kritisk vurdering av AI om tro og livssyn',
        steps: ['AI gir informasjon (10 min)', 'Faktasjekk med pålitelige kilder (25 min)', 'Korriger feil sammen (10 min)'],
      },
      {
        title: 'Livsmestring og refleksjon',
        duration: '45 min',
        goal: 'Koble personlig refleksjon til faglige temaer',
        steps: ['Reflect-aktivitet (15 min)', 'Skriftlig refleksjon (20 min)', 'Valgfri deling (10 min)'],
      },
    ],
    prompts: [
      'Lag et etisk dilemma om [tema] for 8. trinn. Inkluder refleksjonsspørsmål – ikke fasitsvar.',
      'Hvilke verdier er i konflikt i denne situasjonen? Still åpne spørsmål for klassediskusjon.',
      'Hva bør en elev være skeptisk til når de spør AI om religion og livssyn?',
    ],
    assessment: [
      'Vurder refleksjonsdybde – ikke «riktig» mening',
      'Respekt i diskusjon som eksplisitt kriterium',
      'Faktasjekk ved faktapåstander om religion',
      'Prosessvurdering av dialogferdigheter',
    ],
    studentRules: [
      'Vis respekt – AI erstatter ikke menneskelig dialog',
      'Faktasjekk påstander om religion og livssyn',
      'Del ikke personlig sensitive opplysninger med AI',
      'Reflekter selv – AI gir spørsmål, ikke svar på livet',
    ],
    teacherPath: [
      'Test AI-nøyaktighet om pensumtemaer',
      'Sett opp Reflect for klassen',
      'Lag liste over pålitelige kilder',
      'Øv på fasilitering av sensitive diskusjoner',
    ],
  },

  kunst: {
    intro:
      'Kunst og håndverk handler om skaperglede og prosess. AI brukes i idémyldring og analyse – det fysiske håndverket forblir elevens eget.',
    lk20: [
      'Skapende arbeidsprosesser og estetikk',
      'Kunstneriske uttrykk og teknikker',
      'Kulturarv og samtidskunst',
      'Refleksjon over egen skaperglede',
    ],
    tools: [
      { name: 'Copilot Chat', use: 'Bildegenerering for moodboards og idéer' },
      { name: 'Copilot Chat', use: 'Analyse av kunstverk og stilretninger' },
      { name: 'OneNote', use: 'Prosessdokumentasjon med bilder' },
      { name: 'PowerPoint + Copilot', use: 'Presentasjon av prosjekt og refleksjon' },
    ],
    weeks: [
      { week: 1, title: 'Opphavsrett', activity: 'Undervis om AI-bilder og opphavsrett i skapende fag.' },
      { week: 2, title: 'Idéfase', activity: 'Moodboard med AI – eleven velger og utdyper manuelt.' },
      { week: 3, title: 'Prosess', activity: 'Dokumenter skaperglede: foto av arbeid underveis.' },
      { week: 4, title: 'Analyse', activity: 'Analyser kunstverk med AI – eleven skriver egen tolkning.' },
      { week: 5, title: 'Teknikk', activity: 'AI foreslår teknikker – eleven prøver fysisk.' },
      { week: 6, title: 'Refleksjon', activity: '«Hva gjorde jeg selv vs. hva gjorde AI?»' },
      { week: 7, title: 'Utstilling', activity: 'Forbered utstilling med prosesslogg.' },
      { week: 8, title: 'Diskusjon', activity: 'Debatt: Er AI-kunst «ekte» kunst?' },
      { week: 9, title: 'Vurdering', activity: 'Rubrikk vekter håndverk og refleksjon høyest.' },
      { week: 10, title: 'Evaluering', activity: 'Elevrefleksjon om kreativ prosess.' },
    ],
    lessons: [
      {
        title: 'Moodboard for designprosjekt',
        duration: '45 min',
        goal: 'Bruke AI i idéfase, utføre fysisk',
        steps: ['AI genererer 3 retninger (15 min)', 'Velg og tegn/skisse manuelt (25 min)', 'Del valg og begrunnelse (5 min)'],
      },
      {
        title: 'Kunstanalyse',
        duration: '45 min',
        goal: 'Tolk kunstverk med kritisk blikk',
        steps: ['AI gir førsteanalyse (10 min)', 'Eleven skriver egen tolkning (25 min)', 'Sammenlign i par (10 min)'],
      },
      {
        title: 'AI-kunst vs. menneskelig skaperglede',
        duration: '45 min',
        goal: 'Reflektere over teknologi i kunst',
        steps: ['Vis eksempler (10 min)', 'Diskusjon i grupper (25 min)', 'Skriftlig refleksjon (10 min)'],
      },
    ],
    prompts: [
      'Beskriv tre visuelle retninger for et prosjekt om [tema]. Jeg skal lage det fysisk selv.',
      'Analyser dette kunstverket: stil, teknikk, budskap. Jeg skal skrive min egen tolkning etterpå.',
      'Foreslå 5 materialer og teknikker for [prosjekttype] – forklar kort hva hver gir uttrykksmessig.',
    ],
    assessment: [
      'Vektlegg fysisk utførelse og håndverk',
      'Prosessdokumentasjon er obligatorisk',
      'AI-bruk kun i idéfase – merk tydelig',
      'Refleksjon over estetiske valg',
    ],
    studentRules: [
      'AI for idéer – du lager verkets fysiske del',
      'Dokumenter prosessen med bilder',
      'Oppgi om AI-bilder er brukt i planlegging',
      'Respekter opphavsrett ved deling',
    ],
    teacherPath: [
      'Lag retningslinjer for AI i kreative prosesser',
      'Test bildegenerering for egnethet',
      'Utvikle prosesslogg-mal',
      'Planlegg utstilling med refleksjonskrav',
    ],
  },

  programfag: {
    intro:
      'I yrkesfag og programfag møter elevene AI som arbeidsverktøy. GitHub Copilot, agenter og dokumentasjon er sentrale ferdigheter for arbeidslivet.',
    lk20: [
      'Fagspesifikke arbeidsoppgaver og HMS',
      'Digitale ferdigheter og programmering',
      'Bærekraft og innovasjon i bransjen',
      'Livslang læring og karriereutvikling',
    ],
    tools: [
      { name: 'GitHub Copilot', use: 'Paired programming og kodeassistanse' },
      { name: 'Copilot Studio', use: 'Bygge bransjespesifikke agenter' },
      { name: 'Copilot Chat', use: 'Teknisk dokumentasjon og HMS-scenarier' },
      { name: 'Power Automate', use: 'Automatisere arbeidsflyter' },
    ],
    weeks: [
      { week: 1, title: 'Etikk', activity: 'Retningslinjer for AI i koding og fagoppgaver.' },
      { week: 2, title: 'Copilot intro', activity: 'Installér og test GitHub Copilot i kontrollert øvelse.' },
      { week: 3, title: 'Parprogrammering', activity: '2-timers økt: menneske + Copilot.' },
      { week: 4, title: 'Debugging', activity: 'Bruk AI til feilsøking – eleven forklarer løsningen.' },
      { week: 5, title: 'Agent', activity: 'Bygg enkel agent i Copilot Studio for faglig use case.' },
      { week: 6, title: 'Dokumentasjon', activity: 'Generer teknisk dokumentasjon – kurater og korriger.' },
      { week: 7, title: 'HMS', activity: 'AI-scenarier for sikkerhet på arbeidsplassen.' },
      { week: 8, title: 'Bransje', activity: 'Gjesteforedrag eller research: AI i bransjen.' },
      { week: 9, title: 'Prosjekt', activity: 'Fagprosjekt med dokumentert AI-bruk.' },
      { week: 10, title: 'Karriere', activity: 'Refleksjon: AI-kompetanse i jobbsøking.' },
    ],
    lessons: [
      {
        title: 'Paired programming med Copilot',
        duration: '2 × 45 min',
        goal: 'Ansvarlig bruk av AI i koding',
        steps: ['Etikk og regler (20 min)', 'Praktisk øvelse i par (50 min)', 'Code review og refleksjon (20 min)'],
      },
      {
        title: 'Bygg en enkel agent',
        duration: '2 × 45 min',
        goal: 'Forstå agentic AI i praksis',
        steps: ['Intro Copilot Studio (30 min)', 'Bygg agent for [use case] (45 min)', 'Test og presenter (15 min)'],
      },
      {
        title: 'HMS-scenario med AI',
        duration: '45 min',
        goal: 'Vurdere risiko og sikkerhetstiltak',
        steps: ['AI beskriver scenario (10 min)', 'Grupper vurderer tiltak (25 min)', 'Presentasjon (10 min)'],
      },
    ],
    prompts: [
      'Hjelp meg debugge denne koden. Forklar feilen – la meg fikse den selv.',
      'Skriv dokumentasjon for dette programmet. Jeg skal verifisere teknisk nøyaktighet.',
      'Design en 2-timers økt om paired programming med GitHub Copilot for VG2 IT.',
    ],
    assessment: [
      'Vurder forståelse av kode – ikke bare fungerende program',
      'Krev forklaring muntlig av AI-assistert løsning',
      'Dokumenter AI-bruk i prosjektrapport',
      'HMS-vurdering i praktiske oppgaver',
    ],
    studentRules: [
      'Forstå koden du leverer – ikke kopier blindt',
      'Dokumenter Copilot-bruk i prosjekter',
      'Følg bransjens etikk og HMS-regler',
      'AI er verktøy – du er fagpersonen',
    ],
    teacherPath: [
      'Sett opp GitHub Education for klassen',
      'Fullfør GitHub Copilot-kurset selv',
      'Test Copilot Studio for ett use case',
      'Koble med lokalt næringsliv om AI-trends',
    ],
  },
};
